# Generated by Django 3.1.7 on 2021-05-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('field_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('prject_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
