# Generated by Django 3.1.7 on 2021-05-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_board', '0002_auto_20210516_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('field_id', models.TextField()),
            ],
        ),
    ]
