# Generated by Django 3.1.7 on 2021-05-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira_board', '0003_jirauser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jirauser',
            name='field_id',
        ),
    ]
