# Generated by Django 3.1.7 on 2021-05-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_board', '0004_remove_jirauser_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jirauser',
            name='account_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
